name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: appala.deepak@straive.com
        run: echo "Hello, world!"
      - name:appala.deepak@straive.com
        run: echo "Hello, world!"
